### ISSUE TITLE
Support mochi-1 preview

### ISSUE THREAD

**Issue by XueZeyue** [VideoVerses/VideoTuna#1]
Thanks for your nice work!
May I ask when will you support fine-tuning mochi-1 preview (https://github.com/genmoai/models)?

**Comment by YingqingHe** [comment]
Thanks for your message and valuable comments! We will support the fine-tuning of Mochi-1 as soon as possible, within about two weeks.

**Comment by WangWenhao0716** [comment]
Hi Cassie,  How about the progress of supporting Mochi-1?😊
