### ISSUE TITLE
Some small bugs when training videocrafter2

### ISSUE THREAD

**Issue by Vincent-luo** [VideoVerses/VideoTuna#13]
Thansks for this great project!

After doing some training with videocrafter2, I found some bugs.
1. can't train text encoder even if set `cond_stage_trainable: true` in config. Refer to [these lines](https://github.com/VideoVerses/VideoTuna/blob/b8e1b9fd143b17bb168e64244bea499b0943bdbb/src/base/ddpm3d.py#L604-L642), text encoding process(`get_learned_conditioning`) is under `torch.no_grad()`, so no grad is computed. Simple fix is just remove the `@torch.no_grad()`
```
    @torch.no_grad()
    def get_batch_input(self, batch, random_uncond, return_first_stage_outputs=False, return_original_cond=False, is_imgbatch=False):
        ...

        if isinstance(cond, dict) or isinstance(cond, list):
            cond_emb = self.get_learned_conditioning(cond)
        else:
            cond_emb = self.get_learned_conditioning(cond.to(self.device))
        ...
```

2. in some shell scripts there is line like `--auto_resume True`(like this [line](https://github.com/VideoVerses/VideoTuna/blob/b8e1b9fd143b17bb168e64244bea499b0943bdbb/shscripts/train_videocrafter_v2.sh#L23)), actually we don't need "True" here. auto_resume is a flag with no arguement, if it exist it's true, otherwise it's false.

3. same logging message printed twice, seems like the mainlogger inherits the root logger's handler. Simple fix is set "    logger.propagate = False" in [set_logger](https://github.com/VideoVerses/VideoTuna/blob/b8e1b9fd143b17bb168e64244bea499b0943bdbb/src/utils/train_utils.py#L270).

**Comment by YingqingHe** [comment]
Hii Vincent. Thanks for your valuable comments! We have fixed these issues in our code!! Feel free to give any other comments while using this codebase. Thanks!
