### ISSUE TITLE
Video compression and reconstruction

### ISSUE THREAD

**Issue by jayhsu0627** [VideoVerses/VideoTuna#20]
Hi 
Thanks for the great work.
May I ask a question regarding the example videos you showed in your readme? How can we re-implement the compression and reconstruction? Does it use this repo (https://www.modelscope.cn/models/iic/Video-to-Video/summary) or you're using the 3D Causal VAE from CogVid?

Best!

**Comment by yzxing87** [comment]
hi, the vae demo in our repo is obtained by our own vae model. We will release the model weight soon.
